"""empty message

Revision ID: 895b6e260711
Revises: d41020225689
Create Date: 2020-07-06 23:33:45.074630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895b6e260711'
down_revision = 'd41020225689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
