"""empty message

Revision ID: f5eb1fb08642
Revises: b28246d73779
Create Date: 2020-07-07 18:20:14.290589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5eb1fb08642'
down_revision = 'b28246d73779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('sttart_time', sa.DateTime(), nullable=False))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('show', 'sttart_time')
    # ### end Alembic commands ###
